Repository boostcamp-2020/Project11-C-Web-FE-Performance-Monitoring-Server, pull requests merged in 2020-12, with the labels that each got.

#27 Oauth 기능 구현
  package.json
  src/controllers/LoginController.ts
  src/controllers/UserController.ts
  src/passport.ts
  src/routes/UserRoute.ts
  src/routes/index.ts
  src/services/LoginService.ts
  src/services/UserService.ts
  yarn.lock
Labels: backend, feature

#28 프로젝트 api 구현 & 권한 설정 api
  src/controllers/LoginController.ts
  src/controllers/ProjectController.ts
  src/controllers/UserController.ts
  src/passport.ts
  src/routes/ProjectRoute.ts
  src/routes/UserRoute.ts
  src/routes/index.ts
  src/services/LoginService.ts
  src/services/ProjectService.ts
  src/services/UserService.ts
Labels: backend, feature

#29 errorevent, issue 관련 기본 기능 구현
  src/controllers/ErrorEventController.ts
  src/controllers/IssueController.ts
  src/controllers/LogControllers.ts
  src/models/ErrorEvent.ts
  src/models/Issue.ts
  src/models/Log.ts
  src/routes/Error.ts
  src/routes/Issue.ts
  src/routes/index.ts
  src/services/ErrorEventService.ts
  src/services/IssueService.ts
Labels: backend

#30 comment crud 구현, Issue,ErrorEvent Schema 변경
  src/app.ts
  src/controllers/CommentController.ts
  src/models/Comment.ts
  src/models/ErrorEvent.ts
  src/models/Issue.ts
  src/routes/Issue.ts
  src/routes/index.ts
  src/services/CommentService.ts
  src/services/ErrorEventService.ts
  src/services/IssueService.ts
Labels: backend, enhancement, feature

#31 Readme 추가
  README.md
Labels: documentation

#32 error endpoint에 dsn 적용, issue api 추가 등
  src/controllers/ErrorEventController.ts
  src/controllers/IssueController.ts
  src/models/ErrorEvent.ts
  src/models/Issue.ts
  src/routes/Error.ts
  src/routes/Issue.ts
  src/services/ErrorEventService.ts
  src/services/IssueService.ts
  src/services/ProjectService.ts
Labels: backend, enhancement, feature

#34 readProjects response 데이터 변경
  src/services/UserService.ts
Labels: backend

#35 이슈 담당자 지정/변경 , 이슈 해결상태 변경 api 추가
  src/controllers/IssueController.ts
  src/controllers/ProjectController.ts
  src/models/Issue.ts
  src/routes/Issue.ts
  src/routes/ProjectRoute.ts
  src/services/IssueService.ts
  src/services/ProjectService.ts
Labels: backend, enhancement, feature

#36 `framework`를 `platform`으로 변경
  src/models/Project.ts
  src/services/ProjectService.ts
  src/services/UserService.ts
Labels: backend

#41 issue 해결상태, 마감기한 수정 api 개선, 각종 버그수정
  src/controllers/IssueController.ts
  src/controllers/LoginController.ts
  src/models/Issue.ts
  src/routes/Issue.ts
  src/services/IssueService.ts
Labels: backend, bug, enhancement

#49 alert(새 이슈발생시) , 메일전송, issue pagination 구현
  src/controllers/AlertController.ts
  src/controllers/IssueController.ts
  src/mailConfig.ts
  src/models/Alert.ts
  src/models/Issue.ts
  src/models/Project.ts
  src/models/User.ts
  src/routes/Alert.ts
  src/routes/Issue.ts
  src/routes/index.ts
  src/services/AlertService.ts
  src/services/IssueService.ts
  src/services/MailService.ts
  src/services/ProjectService.ts
  tsconfig.json
Labels: backend, enhancement, feature

#50 Stats API 구현
  package.json
  src/controllers/ChartController.ts
  src/models/User.ts
  src/routes/ProjectRoute.ts
  src/services/ChartService.ts
  yarn.lock
Labels: backend, feature

#53 alert list 반환 api 변경
  src/models/Alert.ts
  src/services/AlertService.ts
Labels: backend, enhancement, feature
