Repository boostcamp-2020/Project11-C-Web-FE-Performance-Monitoring-Server, pull requests merged in 2020-11, with the labels that each got.

#18 docker 관련 디렉토리 추가, docker-compose file 작성
  .gitignore
  docker/docker-compose.yml
Labels: backend

#20 Readme 추가
  README.md
Labels: documentation

#19 Oauth 인증(used passport) + 쿠키 발행 + 사용자 이메일 획득
  .gitignore
  package-lock.json
  package.json
  src/app.ts
  src/controllers/LoginController.ts
  src/passport.ts
  src/routes/auth/Login.ts
  src/routes/index.ts
  src/services/LoginService.ts
Labels: backend, feature

#22 mongodb 설정 및 연동, 로그 수집 api구현
  docker/docker-compose.yml
  nodemon.json
  package-lock.json
  package.json
  src/app.ts
  src/controllers/LogControllers.ts
  src/models/Log.ts
  src/mongo.ts
  src/routes/index.ts
  src/routes/log/Log.ts
Labels: backend

#23 네이버 로그인 기능 추가
  package-lock.json
  package.json
  src/controllers/LoginController.ts
  src/passport.ts
  src/routes/auth/Login.ts
  src/services/LoginService.ts
Labels: backend, feature

#25 프로젝트 api 구현
  src/controllers/ProjectController.ts
  src/models/Project.ts
  src/routes/ProjectRoute.ts
  src/routes/index.ts
  src/services/ProjectService.ts
Labels: backend, feature
